# Generated by Django 4.2.10 on 2024-10-29 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(default='', max_length=12)),
                ('second_last_name', models.CharField(default='', max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_telefono', models.CharField(default='', max_length=15)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Vendedor', 'Vendedor')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(default='', max_length=12)),
                ('second_last_name', models.CharField(default='', max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_telefono', models.CharField(default='', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
