# Generated by Django 4.2.10 on 2024-12-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_clienteanonimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteanonimo',
            name='session_key',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
