# Generated by Django 4.2.10 on 2025-04-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_remove_cliente_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteanonimo',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
