# Generated by Django 4.2.10 on 2024-11-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalleOrden',
            new_name='DetalleOrdenCompra',
        ),
    ]
