# Generated by Django 4.2.10 on 2024-12-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0004_alter_detalleventaonline_estado_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Vehículo', 'Vehículo'), ('Otro', 'Otro')], default='Otro', max_length=100),
        ),
    ]
