# Generated by Django 4.2.10 on 2024-12-12 22:45

import apps.Transaccion.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0006_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria_productos/', validators=[apps.Transaccion.models.validar_tamano_imagen])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Transaccion.producto')),
            ],
        ),
    ]
