# Generated by Django 4.2.10 on 2024-12-16 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_clienteanonimo'),
        ('Transaccion', '0008_servicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventamanual',
            name='cliente_anonimo',
            field=models.ForeignKey(blank=True, help_text='Cliente anónimo que realiza la compra.', null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.clienteanonimo'),
        ),
        migrations.AddField(
            model_name='ventaonline',
            name='cliente_anonimo',
            field=models.ForeignKey(blank=True, help_text='Cliente anónimo que realiza la compra.', null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.clienteanonimo'),
        ),
        migrations.AlterField(
            model_name='ventamanual',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente registrado que realiza la compra (opcional para cliente anónimo).', null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.cliente'),
        ),
        migrations.AlterField(
            model_name='ventaonline',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente registrado que realiza la compra (opcional para cliente anónimo).', null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.cliente'),
        ),
    ]
