# Generated by Django 4.2.10 on 2024-12-25 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0011_carrito_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventamanual',
            old_name='orden_venta',
            new_name='orden_compra',
        ),
    ]
