# Generated by Django 4.2.10 on 2025-01-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0012_rename_orden_venta_detalleventamanual_orden_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventaonline',
            name='calculo_tiempo_transcurrido',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleventaonline',
            name='fecha_estado_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
