# Generated by Django 4.2.10 on 2025-01-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0013_detalleventaonline_calculo_tiempo_transcurrido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_extra',
            field=models.PositiveIntegerField(blank=True, help_text='Costos adicionales del producto', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.PositiveIntegerField(blank=True, help_text='Precio de costo del producto', null=True),
        ),
    ]
