# Generated by Django 4.2.10 on 2025-01-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0016_detalleventaonline_dias_desde_adquisicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='precio_costo',
            field=models.PositiveIntegerField(blank=True, help_text='Precio de costo del servicio', null=True),
        ),
    ]
