# Generated by Django 4.2.10 on 2025-01-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0017_servicio_precio_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='precio_costo',
        ),
        migrations.AddField(
            model_name='detalleventamanual',
            name='precio_costo',
            field=models.PositiveIntegerField(blank=True, help_text='Costo asociado a este detalle', null=True),
        ),
    ]
