# Generated by Django 4.2.10 on 2025-01-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0018_remove_servicio_precio_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventamanual',
            name='precio_costo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
