# Generated by Django 4.2.10 on 2025-01-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0019_alter_detalleventamanual_precio_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventamanual',
            name='precio_costo',
            field=models.PositiveIntegerField(blank=True, help_text='Costo asociado a este detalle', null=True),
        ),
    ]
