# Generated by Django 4.2.10 on 2025-01-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0020_alter_detalleventamanual_precio_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventamanual',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se realizó la venta.', null=True),
        ),
    ]
