# Generated by Django 4.2.10 on 2025-01-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0021_alter_ventamanual_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventamanual',
            name='fecha_pago_final',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el pago fue completado.', null=True),
        ),
    ]
