# Generated by Django 4.2.10 on 2025-02-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0022_ventamanual_fecha_pago_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='consignado',
            field=models.BooleanField(default=False, help_text='Indica si el producto está en consignación.'),
        ),
    ]
