# Generated by Django 4.2.10 on 2025-02-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0023_producto_consignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='porcentaje_consignacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de ganancia sobre el precio de venta para productos consignados.', max_digits=5, null=True),
        ),
    ]
