# Generated by Django 4.2.10 on 2025-02-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0024_producto_porcentaje_consignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='porcentaje_consignacion',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Porcentaje de ganancia sobre el precio de venta para productos consignados.', max_digits=30, null=True),
        ),
    ]
