# Generated by Django 4.2.10 on 2025-03-21 22:32

import apps.Transaccion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0027_ventaonline_tbk_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(editable=False, max_length=10, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', validators=[apps.Transaccion.models.validar_tamano_imagen]),
        ),
    ]
