# Generated by Django 4.2.10 on 2025-04-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0029_rename_formularioinspeccion_informeinspeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventamanual',
            name='marca_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalleventamanual',
            name='modelo_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalleventamanual',
            name='patente_vehiculo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
