# Generated by Django 4.2.10 on 2025-04-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0030_detalleventamanual_marca_vehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventaonline',
            name='marca_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalleventaonline',
            name='modelo_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalleventaonline',
            name='patente_vehiculo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
