# Generated by Django 4.2.10 on 2025-04-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaccion', '0031_detalleventaonline_marca_vehiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='patente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
